import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/context/theme-context";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={outfit.className}>
      <ThemeProvider>
        <Toaster />
        <main>{children}</main>
      </ThemeProvider>
      </body>
      </html>
  );
}
