// Shared user data - in a real app, this would come from an API
export const users = [
    {
      id: 1,
      name: "Samanta William",
      email: "samanta@school.com",
      subjects: ["Maths"],
      classes: ["CE1", "CE2"],
      lastLogin: "2025-07-14 10:32",
      content: 12,
      checked: true,
      avatar: "SW",
      status: "active",
    },
    {
      id: 2,
      name: "Tony Soap",
      email: "tony@school.com",
      subjects: ["Physics"],
      classes: ["1Bac-SM"],
      lastLogin: "2025-07-14 10:32",
      content: 20,
      checked: false,
      avatar: "TS",
      status: "active",
    },
    {
      id: 3,
      name: "Karen Hope",
      email: "karen@school.com",
      subjects: ["Arabic"],
      classes: ["2Bac"],
      lastLogin: "2025-07-14 10:32",
      content: 6,
      checked: true,
      avatar: "KH",
      status: "active",
    },
    {
      id: 4,
      name: "Jordan Nico",
      email: "jordan@school.com",
      subjects: ["Physics"],
      classes: ["CP"],
      lastLogin: "2025-07-14 10:32",
      content: 33,
      checked: false,
      avatar: "JN",
      status: "active",
    },
    {
      id: 5,
      name: "Nadila Adja",
      email: "nadila@school.com",
      subjects: ["Maths"],
      classes: ["CE3"],
      lastLogin: "2025-07-14 10:32",
      content: 15,
      checked: true,
      avatar: "NA",
      status: "active",
    },
    {
      id: 6,
      name: "Johnny Ahmad",
      email: "johnny@school.com",
      subjects: ["Physics"],
      classes: ["1Bac-SM"],
      lastLogin: "2025-07-14 10:32",
      content: 8,
      checked: false,
      avatar: "JA",
      status: "blocked",
    },
  ];
  
  export const subjectColors = {
    Maths: "bg-orange-100 text-orange-800",
    Physics: "bg-yellow-100 text-yellow-800",
    Arabic: "bg-purple-100 text-purple-800",
  };
